/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using AssemblyPay.Sdk.Client;
using AssemblyPay.Sdk.Model;

namespace AssemblyPay.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDirectDebitAuthoritiesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Direct Debit Authority
        /// </summary>
        /// <remarks>
        /// Create a **Direct Debit Authority** associated with a **Bank Account**. The **Direct Debit Authority** is required to use a **Bank Account** as a funding source (Direct Debit/ACH). 
        /// </remarks>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="directDebitAuthorityRequestBody"></param>
        /// <returns>SingleDirectDebitAuthority</returns>
        SingleDirectDebitAuthority CreateDirectDebitAuthority(DirectDebitAuthorityRequestBody directDebitAuthorityRequestBody);

        /// <summary>
        /// Create Direct Debit Authority
        /// </summary>
        /// <remarks>
        /// Create a **Direct Debit Authority** associated with a **Bank Account**. The **Direct Debit Authority** is required to use a **Bank Account** as a funding source (Direct Debit/ACH). 
        /// </remarks>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="directDebitAuthorityRequestBody"></param>
        /// <returns>ApiResponse of SingleDirectDebitAuthority</returns>
        ApiResponse<SingleDirectDebitAuthority> CreateDirectDebitAuthorityWithHttpInfo(DirectDebitAuthorityRequestBody directDebitAuthorityRequestBody);
        /// <summary>
        /// List Direct Debit Authorities
        /// </summary>
        /// <remarks>
        /// Retrieve an ordered and paginated list of existing **Direct Debit Authorities**.
        /// </remarks>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Bank account ID</param>
        /// <param name="limit">Number of records to retrieve. Up to 200. (optional, default to 10)</param>
        /// <param name="offset">Number of records to offset. Required for pagination. (optional, default to 0)</param>
        /// <returns>ListDirectDebitAuthorities</returns>
        ListDirectDebitAuthorities ListDirectDebitAuthorities(string accountId, int? limit = default(int?), int? offset = default(int?));

        /// <summary>
        /// List Direct Debit Authorities
        /// </summary>
        /// <remarks>
        /// Retrieve an ordered and paginated list of existing **Direct Debit Authorities**.
        /// </remarks>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Bank account ID</param>
        /// <param name="limit">Number of records to retrieve. Up to 200. (optional, default to 10)</param>
        /// <param name="offset">Number of records to offset. Required for pagination. (optional, default to 0)</param>
        /// <returns>ApiResponse of ListDirectDebitAuthorities</returns>
        ApiResponse<ListDirectDebitAuthorities> ListDirectDebitAuthoritiesWithHttpInfo(string accountId, int? limit = default(int?), int? offset = default(int?));
        /// <summary>
        /// Show Direct Debit Authority
        /// </summary>
        /// <remarks>
        /// Show details of a specific **Direct Debit Authority** using a given &#x60;:id&#x60;.
        /// </remarks>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Direct debit authority ID</param>
        /// <returns>SingleDirectDebitAuthority</returns>
        SingleDirectDebitAuthority ShowDirectDebitAuthority(string id);

        /// <summary>
        /// Show Direct Debit Authority
        /// </summary>
        /// <remarks>
        /// Show details of a specific **Direct Debit Authority** using a given &#x60;:id&#x60;.
        /// </remarks>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Direct debit authority ID</param>
        /// <returns>ApiResponse of SingleDirectDebitAuthority</returns>
        ApiResponse<SingleDirectDebitAuthority> ShowDirectDebitAuthorityWithHttpInfo(string id);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDirectDebitAuthoritiesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create Direct Debit Authority
        /// </summary>
        /// <remarks>
        /// Create a **Direct Debit Authority** associated with a **Bank Account**. The **Direct Debit Authority** is required to use a **Bank Account** as a funding source (Direct Debit/ACH). 
        /// </remarks>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="directDebitAuthorityRequestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SingleDirectDebitAuthority</returns>
        System.Threading.Tasks.Task<SingleDirectDebitAuthority> CreateDirectDebitAuthorityAsync(DirectDebitAuthorityRequestBody directDebitAuthorityRequestBody, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create Direct Debit Authority
        /// </summary>
        /// <remarks>
        /// Create a **Direct Debit Authority** associated with a **Bank Account**. The **Direct Debit Authority** is required to use a **Bank Account** as a funding source (Direct Debit/ACH). 
        /// </remarks>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="directDebitAuthorityRequestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SingleDirectDebitAuthority)</returns>
        System.Threading.Tasks.Task<ApiResponse<SingleDirectDebitAuthority>> CreateDirectDebitAuthorityWithHttpInfoAsync(DirectDebitAuthorityRequestBody directDebitAuthorityRequestBody, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List Direct Debit Authorities
        /// </summary>
        /// <remarks>
        /// Retrieve an ordered and paginated list of existing **Direct Debit Authorities**.
        /// </remarks>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Bank account ID</param>
        /// <param name="limit">Number of records to retrieve. Up to 200. (optional, default to 10)</param>
        /// <param name="offset">Number of records to offset. Required for pagination. (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListDirectDebitAuthorities</returns>
        System.Threading.Tasks.Task<ListDirectDebitAuthorities> ListDirectDebitAuthoritiesAsync(string accountId, int? limit = default(int?), int? offset = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List Direct Debit Authorities
        /// </summary>
        /// <remarks>
        /// Retrieve an ordered and paginated list of existing **Direct Debit Authorities**.
        /// </remarks>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Bank account ID</param>
        /// <param name="limit">Number of records to retrieve. Up to 200. (optional, default to 10)</param>
        /// <param name="offset">Number of records to offset. Required for pagination. (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListDirectDebitAuthorities)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListDirectDebitAuthorities>> ListDirectDebitAuthoritiesWithHttpInfoAsync(string accountId, int? limit = default(int?), int? offset = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Show Direct Debit Authority
        /// </summary>
        /// <remarks>
        /// Show details of a specific **Direct Debit Authority** using a given &#x60;:id&#x60;.
        /// </remarks>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Direct debit authority ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SingleDirectDebitAuthority</returns>
        System.Threading.Tasks.Task<SingleDirectDebitAuthority> ShowDirectDebitAuthorityAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Show Direct Debit Authority
        /// </summary>
        /// <remarks>
        /// Show details of a specific **Direct Debit Authority** using a given &#x60;:id&#x60;.
        /// </remarks>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Direct debit authority ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SingleDirectDebitAuthority)</returns>
        System.Threading.Tasks.Task<ApiResponse<SingleDirectDebitAuthority>> ShowDirectDebitAuthorityWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDirectDebitAuthoritiesApi : IDirectDebitAuthoritiesApiSync, IDirectDebitAuthoritiesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DirectDebitAuthoritiesApi : IDirectDebitAuthoritiesApi
    {
        private AssemblyPay.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DirectDebitAuthoritiesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DirectDebitAuthoritiesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DirectDebitAuthoritiesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DirectDebitAuthoritiesApi(string basePath)
        {
            this.Configuration = AssemblyPay.Sdk.Client.Configuration.MergeConfigurations(
                AssemblyPay.Sdk.Client.GlobalConfiguration.Instance,
                new AssemblyPay.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.Client = new AssemblyPay.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new AssemblyPay.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = AssemblyPay.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DirectDebitAuthoritiesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DirectDebitAuthoritiesApi(AssemblyPay.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = AssemblyPay.Sdk.Client.Configuration.MergeConfigurations(
                AssemblyPay.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new AssemblyPay.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new AssemblyPay.Sdk.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = AssemblyPay.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DirectDebitAuthoritiesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DirectDebitAuthoritiesApi(AssemblyPay.Sdk.Client.ISynchronousClient client, AssemblyPay.Sdk.Client.IAsynchronousClient asyncClient, AssemblyPay.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = AssemblyPay.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public AssemblyPay.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public AssemblyPay.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AssemblyPay.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AssemblyPay.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create Direct Debit Authority Create a **Direct Debit Authority** associated with a **Bank Account**. The **Direct Debit Authority** is required to use a **Bank Account** as a funding source (Direct Debit/ACH). 
        /// </summary>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="directDebitAuthorityRequestBody"></param>
        /// <returns>SingleDirectDebitAuthority</returns>
        public SingleDirectDebitAuthority CreateDirectDebitAuthority(DirectDebitAuthorityRequestBody directDebitAuthorityRequestBody)
        {
            AssemblyPay.Sdk.Client.ApiResponse<SingleDirectDebitAuthority> localVarResponse = CreateDirectDebitAuthorityWithHttpInfo(directDebitAuthorityRequestBody);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Direct Debit Authority Create a **Direct Debit Authority** associated with a **Bank Account**. The **Direct Debit Authority** is required to use a **Bank Account** as a funding source (Direct Debit/ACH). 
        /// </summary>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="directDebitAuthorityRequestBody"></param>
        /// <returns>ApiResponse of SingleDirectDebitAuthority</returns>
        public AssemblyPay.Sdk.Client.ApiResponse<SingleDirectDebitAuthority> CreateDirectDebitAuthorityWithHttpInfo(DirectDebitAuthorityRequestBody directDebitAuthorityRequestBody)
        {
            // verify the required parameter 'directDebitAuthorityRequestBody' is set
            if (directDebitAuthorityRequestBody == null)
            {
                throw new AssemblyPay.Sdk.Client.ApiException(400, "Missing required parameter 'directDebitAuthorityRequestBody' when calling DirectDebitAuthoritiesApi->CreateDirectDebitAuthority");
            }

            AssemblyPay.Sdk.Client.RequestOptions localVarRequestOptions = new AssemblyPay.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AssemblyPay.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AssemblyPay.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = directDebitAuthorityRequestBody;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + AssemblyPay.Sdk.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (oAuth2ClientCredentials) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<SingleDirectDebitAuthority>("/direct_debit_authorities", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateDirectDebitAuthority", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Direct Debit Authority Create a **Direct Debit Authority** associated with a **Bank Account**. The **Direct Debit Authority** is required to use a **Bank Account** as a funding source (Direct Debit/ACH). 
        /// </summary>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="directDebitAuthorityRequestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SingleDirectDebitAuthority</returns>
        public async System.Threading.Tasks.Task<SingleDirectDebitAuthority> CreateDirectDebitAuthorityAsync(DirectDebitAuthorityRequestBody directDebitAuthorityRequestBody, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            AssemblyPay.Sdk.Client.ApiResponse<SingleDirectDebitAuthority> localVarResponse = await CreateDirectDebitAuthorityWithHttpInfoAsync(directDebitAuthorityRequestBody, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Direct Debit Authority Create a **Direct Debit Authority** associated with a **Bank Account**. The **Direct Debit Authority** is required to use a **Bank Account** as a funding source (Direct Debit/ACH). 
        /// </summary>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="directDebitAuthorityRequestBody"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SingleDirectDebitAuthority)</returns>
        public async System.Threading.Tasks.Task<AssemblyPay.Sdk.Client.ApiResponse<SingleDirectDebitAuthority>> CreateDirectDebitAuthorityWithHttpInfoAsync(DirectDebitAuthorityRequestBody directDebitAuthorityRequestBody, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'directDebitAuthorityRequestBody' is set
            if (directDebitAuthorityRequestBody == null)
            {
                throw new AssemblyPay.Sdk.Client.ApiException(400, "Missing required parameter 'directDebitAuthorityRequestBody' when calling DirectDebitAuthoritiesApi->CreateDirectDebitAuthority");
            }


            AssemblyPay.Sdk.Client.RequestOptions localVarRequestOptions = new AssemblyPay.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AssemblyPay.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AssemblyPay.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = directDebitAuthorityRequestBody;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + AssemblyPay.Sdk.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (oAuth2ClientCredentials) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<SingleDirectDebitAuthority>("/direct_debit_authorities", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateDirectDebitAuthority", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Direct Debit Authorities Retrieve an ordered and paginated list of existing **Direct Debit Authorities**.
        /// </summary>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Bank account ID</param>
        /// <param name="limit">Number of records to retrieve. Up to 200. (optional, default to 10)</param>
        /// <param name="offset">Number of records to offset. Required for pagination. (optional, default to 0)</param>
        /// <returns>ListDirectDebitAuthorities</returns>
        public ListDirectDebitAuthorities ListDirectDebitAuthorities(string accountId, int? limit = default(int?), int? offset = default(int?))
        {
            AssemblyPay.Sdk.Client.ApiResponse<ListDirectDebitAuthorities> localVarResponse = ListDirectDebitAuthoritiesWithHttpInfo(accountId, limit, offset);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Direct Debit Authorities Retrieve an ordered and paginated list of existing **Direct Debit Authorities**.
        /// </summary>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Bank account ID</param>
        /// <param name="limit">Number of records to retrieve. Up to 200. (optional, default to 10)</param>
        /// <param name="offset">Number of records to offset. Required for pagination. (optional, default to 0)</param>
        /// <returns>ApiResponse of ListDirectDebitAuthorities</returns>
        public AssemblyPay.Sdk.Client.ApiResponse<ListDirectDebitAuthorities> ListDirectDebitAuthoritiesWithHttpInfo(string accountId, int? limit = default(int?), int? offset = default(int?))
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
            {
                throw new AssemblyPay.Sdk.Client.ApiException(400, "Missing required parameter 'accountId' when calling DirectDebitAuthoritiesApi->ListDirectDebitAuthorities");
            }

            AssemblyPay.Sdk.Client.RequestOptions localVarRequestOptions = new AssemblyPay.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AssemblyPay.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AssemblyPay.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(AssemblyPay.Sdk.Client.ClientUtils.ParameterToMultiMap("", "account_id", accountId));
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(AssemblyPay.Sdk.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(AssemblyPay.Sdk.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + AssemblyPay.Sdk.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (oAuth2ClientCredentials) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListDirectDebitAuthorities>("/direct_debit_authorities", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListDirectDebitAuthorities", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Direct Debit Authorities Retrieve an ordered and paginated list of existing **Direct Debit Authorities**.
        /// </summary>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Bank account ID</param>
        /// <param name="limit">Number of records to retrieve. Up to 200. (optional, default to 10)</param>
        /// <param name="offset">Number of records to offset. Required for pagination. (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListDirectDebitAuthorities</returns>
        public async System.Threading.Tasks.Task<ListDirectDebitAuthorities> ListDirectDebitAuthoritiesAsync(string accountId, int? limit = default(int?), int? offset = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            AssemblyPay.Sdk.Client.ApiResponse<ListDirectDebitAuthorities> localVarResponse = await ListDirectDebitAuthoritiesWithHttpInfoAsync(accountId, limit, offset, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Direct Debit Authorities Retrieve an ordered and paginated list of existing **Direct Debit Authorities**.
        /// </summary>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="accountId">Bank account ID</param>
        /// <param name="limit">Number of records to retrieve. Up to 200. (optional, default to 10)</param>
        /// <param name="offset">Number of records to offset. Required for pagination. (optional, default to 0)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListDirectDebitAuthorities)</returns>
        public async System.Threading.Tasks.Task<AssemblyPay.Sdk.Client.ApiResponse<ListDirectDebitAuthorities>> ListDirectDebitAuthoritiesWithHttpInfoAsync(string accountId, int? limit = default(int?), int? offset = default(int?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'accountId' is set
            if (accountId == null)
            {
                throw new AssemblyPay.Sdk.Client.ApiException(400, "Missing required parameter 'accountId' when calling DirectDebitAuthoritiesApi->ListDirectDebitAuthorities");
            }


            AssemblyPay.Sdk.Client.RequestOptions localVarRequestOptions = new AssemblyPay.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AssemblyPay.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AssemblyPay.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(AssemblyPay.Sdk.Client.ClientUtils.ParameterToMultiMap("", "account_id", accountId));
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(AssemblyPay.Sdk.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(AssemblyPay.Sdk.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + AssemblyPay.Sdk.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (oAuth2ClientCredentials) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ListDirectDebitAuthorities>("/direct_debit_authorities", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListDirectDebitAuthorities", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Show Direct Debit Authority Show details of a specific **Direct Debit Authority** using a given &#x60;:id&#x60;.
        /// </summary>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Direct debit authority ID</param>
        /// <returns>SingleDirectDebitAuthority</returns>
        public SingleDirectDebitAuthority ShowDirectDebitAuthority(string id)
        {
            AssemblyPay.Sdk.Client.ApiResponse<SingleDirectDebitAuthority> localVarResponse = ShowDirectDebitAuthorityWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Show Direct Debit Authority Show details of a specific **Direct Debit Authority** using a given &#x60;:id&#x60;.
        /// </summary>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Direct debit authority ID</param>
        /// <returns>ApiResponse of SingleDirectDebitAuthority</returns>
        public AssemblyPay.Sdk.Client.ApiResponse<SingleDirectDebitAuthority> ShowDirectDebitAuthorityWithHttpInfo(string id)
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new AssemblyPay.Sdk.Client.ApiException(400, "Missing required parameter 'id' when calling DirectDebitAuthoritiesApi->ShowDirectDebitAuthority");
            }

            AssemblyPay.Sdk.Client.RequestOptions localVarRequestOptions = new AssemblyPay.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AssemblyPay.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AssemblyPay.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", AssemblyPay.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + AssemblyPay.Sdk.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (oAuth2ClientCredentials) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<SingleDirectDebitAuthority>("/direct_debit_authorities/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShowDirectDebitAuthority", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Show Direct Debit Authority Show details of a specific **Direct Debit Authority** using a given &#x60;:id&#x60;.
        /// </summary>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Direct debit authority ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SingleDirectDebitAuthority</returns>
        public async System.Threading.Tasks.Task<SingleDirectDebitAuthority> ShowDirectDebitAuthorityAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            AssemblyPay.Sdk.Client.ApiResponse<SingleDirectDebitAuthority> localVarResponse = await ShowDirectDebitAuthorityWithHttpInfoAsync(id, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Show Direct Debit Authority Show details of a specific **Direct Debit Authority** using a given &#x60;:id&#x60;.
        /// </summary>
        /// <exception cref="AssemblyPay.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">Direct debit authority ID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SingleDirectDebitAuthority)</returns>
        public async System.Threading.Tasks.Task<AssemblyPay.Sdk.Client.ApiResponse<SingleDirectDebitAuthority>> ShowDirectDebitAuthorityWithHttpInfoAsync(string id, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new AssemblyPay.Sdk.Client.ApiException(400, "Missing required parameter 'id' when calling DirectDebitAuthoritiesApi->ShowDirectDebitAuthority");
            }


            AssemblyPay.Sdk.Client.RequestOptions localVarRequestOptions = new AssemblyPay.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AssemblyPay.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = AssemblyPay.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", AssemblyPay.Sdk.Client.ClientUtils.ParameterToString(id)); // path parameter

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + AssemblyPay.Sdk.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (oAuth2ClientCredentials) required
            // oauth required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<SingleDirectDebitAuthority>("/direct_debit_authorities/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ShowDirectDebitAuthority", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
