/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace AssemblyPay.Sdk.Model
{
    /// <summary>
    /// SingleCallbackResponse
    /// </summary>
    [DataContract(Name = "single_callback_response")]
    public partial class SingleCallbackResponse : IEquatable<SingleCallbackResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SingleCallbackResponse" /> class.
        /// </summary>
        /// <param name="callResponses">callResponses.</param>
        public SingleCallbackResponse(CallbackResponse callResponses = default(CallbackResponse))
        {
            this.CallResponses = callResponses;
        }

        /// <summary>
        /// Gets or Sets CallResponses
        /// </summary>
        [DataMember(Name = "call_responses", EmitDefaultValue = false)]
        public CallbackResponse CallResponses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SingleCallbackResponse {\n");
            sb.Append("  CallResponses: ").Append(CallResponses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SingleCallbackResponse);
        }

        /// <summary>
        /// Returns true if SingleCallbackResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of SingleCallbackResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SingleCallbackResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CallResponses == input.CallResponses ||
                    (this.CallResponses != null &&
                    this.CallResponses.Equals(input.CallResponses))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CallResponses != null)
                {
                    hashCode = (hashCode * 59) + this.CallResponses.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
