/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace AssemblyPay.Sdk.Model
{
    /// <summary>
    /// SingleCallback
    /// </summary>
    [DataContract(Name = "single_callback")]
    public partial class SingleCallback : IEquatable<SingleCallback>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SingleCallback" /> class.
        /// </summary>
        /// <param name="callbacks">callbacks.</param>
        public SingleCallback(Callback callbacks = default(Callback))
        {
            this.Callbacks = callbacks;
        }

        /// <summary>
        /// Gets or Sets Callbacks
        /// </summary>
        [DataMember(Name = "callbacks", EmitDefaultValue = false)]
        public Callback Callbacks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SingleCallback {\n");
            sb.Append("  Callbacks: ").Append(Callbacks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SingleCallback);
        }

        /// <summary>
        /// Returns true if SingleCallback instances are equal
        /// </summary>
        /// <param name="input">Instance of SingleCallback to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SingleCallback input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Callbacks == input.Callbacks ||
                    (this.Callbacks != null &&
                    this.Callbacks.Equals(input.Callbacks))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Callbacks != null)
                {
                    hashCode = (hashCode * 59) + this.Callbacks.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
