/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SingleDisbursement
    /// </summary>
    [DataContract(Name = "single_disbursement")]
    public partial class SingleDisbursement : IEquatable<SingleDisbursement>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SingleDisbursement" /> class.
        /// </summary>
        /// <param name="disbursements">disbursements.</param>
        public SingleDisbursement(Disbursement disbursements = default(Disbursement))
        {
            this.Disbursements = disbursements;
        }

        /// <summary>
        /// Gets or Sets Disbursements
        /// </summary>
        [DataMember(Name = "disbursements", EmitDefaultValue = false)]
        public Disbursement Disbursements { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SingleDisbursement {\n");
            sb.Append("  Disbursements: ").Append(Disbursements).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SingleDisbursement);
        }

        /// <summary>
        /// Returns true if SingleDisbursement instances are equal
        /// </summary>
        /// <param name="input">Instance of SingleDisbursement to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SingleDisbursement input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Disbursements == input.Disbursements ||
                    (this.Disbursements != null &&
                    this.Disbursements.Equals(input.Disbursements))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Disbursements != null)
                {
                    hashCode = (hashCode * 59) + this.Disbursements.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
