/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing BPayAccountsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BPayAccountsApiTests : IDisposable
    {
        private BPayAccountsApi instance;

        public BPayAccountsApiTests()
        {
            instance = new BPayAccountsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BPayAccountsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BPayAccountsApi
            //Assert.IsType<BPayAccountsApi>(instance);
        }

        /// <summary>
        /// Test CreateBPayAccount
        /// </summary>
        [Fact]
        public void CreateBPayAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BpayAccountRequestBody bpayAccountRequestBody = null;
            //var response = instance.CreateBPayAccount(bpayAccountRequestBody);
            //Assert.IsType<BpayAccount>(response);
        }

        /// <summary>
        /// Test RedactBPayAccount
        /// </summary>
        [Fact]
        public void RedactBPayAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.RedactBPayAccount(id);
            //Assert.IsType<BpayAccountDeletion>(response);
        }

        /// <summary>
        /// Test ShowBPayAccount
        /// </summary>
        [Fact]
        public void ShowBPayAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ShowBPayAccount(id);
            //Assert.IsType<BpayAccount>(response);
        }

        /// <summary>
        /// Test ShowBPayAccountUser
        /// </summary>
        [Fact]
        public void ShowBPayAccountUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ShowBPayAccountUser(id);
            //Assert.IsType<SingleUser>(response);
        }
    }
}
