/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace AssemblyPay.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing BankAccountDeletion
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BankAccountDeletionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BankAccountDeletion
        //private BankAccountDeletion instance;

        public BankAccountDeletionTests()
        {
            // TODO uncomment below to create an instance of BankAccountDeletion
            //instance = new BankAccountDeletion();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BankAccountDeletion
        /// </summary>
        [Fact]
        public void BankAccountDeletionInstanceTest()
        {
            // TODO uncomment below to test "IsType" BankAccountDeletion
            //Assert.IsType<BankAccountDeletion>(instance);
        }


        /// <summary>
        /// Test the property 'BankAccount'
        /// </summary>
        [Fact]
        public void BankAccountTest()
        {
            // TODO unit test for the property 'BankAccount'
        }

    }

}
