/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace AssemblyPay.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing BatchTransactionRelated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchTransactionRelatedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchTransactionRelated
        //private BatchTransactionRelated instance;

        public BatchTransactionRelatedTests()
        {
            // TODO uncomment below to create an instance of BatchTransactionRelated
            //instance = new BatchTransactionRelated();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchTransactionRelated
        /// </summary>
        [Fact]
        public void BatchTransactionRelatedInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchTransactionRelated
            //Assert.IsType<BatchTransactionRelated>(instance);
        }


        /// <summary>
        /// Test the property 'AccountTo'
        /// </summary>
        [Fact]
        public void AccountToTest()
        {
            // TODO unit test for the property 'AccountTo'
        }

    }

}
