/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace AssemblyPay.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing BillPaymentRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BillPaymentRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BillPaymentRequestBody
        //private BillPaymentRequestBody instance;

        public BillPaymentRequestBodyTests()
        {
            // TODO uncomment below to create an instance of BillPaymentRequestBody
            //instance = new BillPaymentRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BillPaymentRequestBody
        /// </summary>
        [Fact]
        public void BillPaymentRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" BillPaymentRequestBody
            //Assert.IsType<BillPaymentRequestBody>(instance);
        }


        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

    }

}
