/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CardAccountRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CardAccountRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CardAccountRequestBody
        //private CardAccountRequestBody instance;

        public CardAccountRequestBodyTests()
        {
            // TODO uncomment below to create an instance of CardAccountRequestBody
            //instance = new CardAccountRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CardAccountRequestBody
        /// </summary>
        [Fact]
        public void CardAccountRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" CardAccountRequestBody
            //Assert.IsType<CardAccountRequestBody>(instance);
        }


        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'ExpiryMonth'
        /// </summary>
        [Fact]
        public void ExpiryMonthTest()
        {
            // TODO unit test for the property 'ExpiryMonth'
        }
        /// <summary>
        /// Test the property 'ExpiryYear'
        /// </summary>
        [Fact]
        public void ExpiryYearTest()
        {
            // TODO unit test for the property 'ExpiryYear'
        }
        /// <summary>
        /// Test the property 'Cvv'
        /// </summary>
        [Fact]
        public void CvvTest()
        {
            // TODO unit test for the property 'Cvv'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

    }

}
