/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CardAccountCardAccountsLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CardAccountCardAccountsLinksTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CardAccountCardAccountsLinks
        //private CardAccountCardAccountsLinks instance;

        public CardAccountCardAccountsLinksTests()
        {
            // TODO uncomment below to create an instance of CardAccountCardAccountsLinks
            //instance = new CardAccountCardAccountsLinks();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CardAccountCardAccountsLinks
        /// </summary>
        [Fact]
        public void CardAccountCardAccountsLinksInstanceTest()
        {
            // TODO uncomment below to test "IsType" CardAccountCardAccountsLinks
            //Assert.IsType<CardAccountCardAccountsLinks>(instance);
        }


        /// <summary>
        /// Test the property 'Self'
        /// </summary>
        [Fact]
        public void SelfTest()
        {
            // TODO unit test for the property 'Self'
        }
        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [Fact]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }

    }

}
