/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CardAccountDeletion
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CardAccountDeletionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CardAccountDeletion
        //private CardAccountDeletion instance;

        public CardAccountDeletionTests()
        {
            // TODO uncomment below to create an instance of CardAccountDeletion
            //instance = new CardAccountDeletion();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CardAccountDeletion
        /// </summary>
        [Fact]
        public void CardAccountDeletionInstanceTest()
        {
            // TODO uncomment below to test "IsType" CardAccountDeletion
            //Assert.IsType<CardAccountDeletion>(instance);
        }


        /// <summary>
        /// Test the property 'CardAccount'
        /// </summary>
        [Fact]
        public void CardAccountTest()
        {
            // TODO unit test for the property 'CardAccount'
        }

    }

}
