/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CardAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CardAccountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CardAccount
        //private CardAccount instance;

        public CardAccountTests()
        {
            // TODO uncomment below to create an instance of CardAccount
            //instance = new CardAccount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CardAccount
        /// </summary>
        [Fact]
        public void CardAccountInstanceTest()
        {
            // TODO uncomment below to test "IsType" CardAccount
            //Assert.IsType<CardAccount>(instance);
        }


        /// <summary>
        /// Test the property 'CardAccounts'
        /// </summary>
        [Fact]
        public void CardAccountsTest()
        {
            // TODO unit test for the property 'CardAccounts'
        }

    }

}
