/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace AssemblyPay.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Charge
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChargeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Charge
        //private Charge instance;

        public ChargeTests()
        {
            // TODO uncomment below to create an instance of Charge
            //instance = new Charge();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Charge
        /// </summary>
        [Fact]
        public void ChargeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Charge
            //Assert.IsType<Charge>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CustomDescriptor'
        /// </summary>
        [Fact]
        public void CustomDescriptorTest()
        {
            // TODO unit test for the property 'CustomDescriptor'
        }
        /// <summary>
        /// Test the property 'CustomData'
        /// </summary>
        [Fact]
        public void CustomDataTest()
        {
            // TODO unit test for the property 'CustomData'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'BuyerFees'
        /// </summary>
        [Fact]
        public void BuyerFeesTest()
        {
            // TODO unit test for the property 'BuyerFees'
        }
        /// <summary>
        /// Test the property 'SellerFees'
        /// </summary>
        [Fact]
        public void SellerFeesTest()
        {
            // TODO unit test for the property 'SellerFees'
        }
        /// <summary>
        /// Test the property 'CreditCardFee'
        /// </summary>
        [Fact]
        public void CreditCardFeeTest()
        {
            // TODO unit test for the property 'CreditCardFee'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'DynamicDescriptor'
        /// </summary>
        [Fact]
        public void DynamicDescriptorTest()
        {
            // TODO unit test for the property 'DynamicDescriptor'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Fact]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
        /// <summary>
        /// Test the property 'PromisepayFee'
        /// </summary>
        [Fact]
        public void PromisepayFeeTest()
        {
            // TODO unit test for the property 'PromisepayFee'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Fact]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'BuyerName'
        /// </summary>
        [Fact]
        public void BuyerNameTest()
        {
            // TODO unit test for the property 'BuyerName'
        }
        /// <summary>
        /// Test the property 'BuyerEmail'
        /// </summary>
        [Fact]
        public void BuyerEmailTest()
        {
            // TODO unit test for the property 'BuyerEmail'
        }
        /// <summary>
        /// Test the property 'BuyerZip'
        /// </summary>
        [Fact]
        public void BuyerZipTest()
        {
            // TODO unit test for the property 'BuyerZip'
        }
        /// <summary>
        /// Test the property 'BuyerCountry'
        /// </summary>
        [Fact]
        public void BuyerCountryTest()
        {
            // TODO unit test for the property 'BuyerCountry'
        }
        /// <summary>
        /// Test the property 'SellerName'
        /// </summary>
        [Fact]
        public void SellerNameTest()
        {
            // TODO unit test for the property 'SellerName'
        }
        /// <summary>
        /// Test the property 'SellerEmail'
        /// </summary>
        [Fact]
        public void SellerEmailTest()
        {
            // TODO unit test for the property 'SellerEmail'
        }
        /// <summary>
        /// Test the property 'SellerZip'
        /// </summary>
        [Fact]
        public void SellerZipTest()
        {
            // TODO unit test for the property 'SellerZip'
        }
        /// <summary>
        /// Test the property 'SellerCountry'
        /// </summary>
        [Fact]
        public void SellerCountryTest()
        {
            // TODO unit test for the property 'SellerCountry'
        }
        /// <summary>
        /// Test the property 'Related'
        /// </summary>
        [Fact]
        public void RelatedTest()
        {
            // TODO unit test for the property 'Related'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
