/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DirectDebitAuthorityRelated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DirectDebitAuthorityRelatedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DirectDebitAuthorityRelated
        //private DirectDebitAuthorityRelated instance;

        public DirectDebitAuthorityRelatedTests()
        {
            // TODO uncomment below to create an instance of DirectDebitAuthorityRelated
            //instance = new DirectDebitAuthorityRelated();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DirectDebitAuthorityRelated
        /// </summary>
        [Fact]
        public void DirectDebitAuthorityRelatedInstanceTest()
        {
            // TODO uncomment below to test "IsType" DirectDebitAuthorityRelated
            //Assert.IsType<DirectDebitAuthorityRelated>(instance);
        }


        /// <summary>
        /// Test the property 'BankAccounts'
        /// </summary>
        [Fact]
        public void BankAccountsTest()
        {
            // TODO unit test for the property 'BankAccounts'
        }

    }

}
