/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace AssemblyPay.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DisbursementLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DisbursementLinksTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DisbursementLinks
        //private DisbursementLinks instance;

        public DisbursementLinksTests()
        {
            // TODO uncomment below to create an instance of DisbursementLinks
            //instance = new DisbursementLinks();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DisbursementLinks
        /// </summary>
        [Fact]
        public void DisbursementLinksInstanceTest()
        {
            // TODO uncomment below to test "IsType" DisbursementLinks
            //Assert.IsType<DisbursementLinks>(instance);
        }


        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Fact]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }
        /// <summary>
        /// Test the property 'WalletAccounts'
        /// </summary>
        [Fact]
        public void WalletAccountsTest()
        {
            // TODO unit test for the property 'WalletAccounts'
        }
        /// <summary>
        /// Test the property 'PaypalAccounts'
        /// </summary>
        [Fact]
        public void PaypalAccountsTest()
        {
            // TODO unit test for the property 'PaypalAccounts'
        }
        /// <summary>
        /// Test the property 'BankAccounts'
        /// </summary>
        [Fact]
        public void BankAccountsTest()
        {
            // TODO unit test for the property 'BankAccounts'
        }
        /// <summary>
        /// Test the property 'BpayAccounts'
        /// </summary>
        [Fact]
        public void BpayAccountsTest()
        {
            // TODO unit test for the property 'BpayAccounts'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'Users'
        /// </summary>
        [Fact]
        public void UsersTest()
        {
            // TODO unit test for the property 'Users'
        }

    }

}
