/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace AssemblyPay.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing FeeRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeeRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FeeRequestBody
        //private FeeRequestBody instance;

        public FeeRequestBodyTests()
        {
            // TODO uncomment below to create an instance of FeeRequestBody
            //instance = new FeeRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FeeRequestBody
        /// </summary>
        [Fact]
        public void FeeRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" FeeRequestBody
            //Assert.IsType<FeeRequestBody>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'FeeTypeId'
        /// </summary>
        [Fact]
        public void FeeTypeIdTest()
        {
            // TODO unit test for the property 'FeeTypeId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Cap'
        /// </summary>
        [Fact]
        public void CapTest()
        {
            // TODO unit test for the property 'Cap'
        }
        /// <summary>
        /// Test the property 'Min'
        /// </summary>
        [Fact]
        public void MinTest()
        {
            // TODO unit test for the property 'Min'
        }
        /// <summary>
        /// Test the property 'Max'
        /// </summary>
        [Fact]
        public void MaxTest()
        {
            // TODO unit test for the property 'Max'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

    }

}
