/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace AssemblyPay.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ItemRelated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemRelatedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ItemRelated
        //private ItemRelated instance;

        public ItemRelatedTests()
        {
            // TODO uncomment below to create an instance of ItemRelated
            //instance = new ItemRelated();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemRelated
        /// </summary>
        [Fact]
        public void ItemRelatedInstanceTest()
        {
            // TODO uncomment below to test "IsType" ItemRelated
            //Assert.IsType<ItemRelated>(instance);
        }


        /// <summary>
        /// Test the property 'Buyers'
        /// </summary>
        [Fact]
        public void BuyersTest()
        {
            // TODO unit test for the property 'Buyers'
        }
        /// <summary>
        /// Test the property 'Sellers'
        /// </summary>
        [Fact]
        public void SellersTest()
        {
            // TODO unit test for the property 'Sellers'
        }

    }

}
