/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing MarketplaceMarketplacesBusinessInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MarketplaceMarketplacesBusinessInformationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MarketplaceMarketplacesBusinessInformation
        //private MarketplaceMarketplacesBusinessInformation instance;

        public MarketplaceMarketplacesBusinessInformationTests()
        {
            // TODO uncomment below to create an instance of MarketplaceMarketplacesBusinessInformation
            //instance = new MarketplaceMarketplacesBusinessInformation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MarketplaceMarketplacesBusinessInformation
        /// </summary>
        [Fact]
        public void MarketplaceMarketplacesBusinessInformationInstanceTest()
        {
            // TODO uncomment below to test "IsType" MarketplaceMarketplacesBusinessInformation
            //Assert.IsType<MarketplaceMarketplacesBusinessInformation>(instance);
        }


        /// <summary>
        /// Test the property 'PrincipalName'
        /// </summary>
        [Fact]
        public void PrincipalNameTest()
        {
            // TODO unit test for the property 'PrincipalName'
        }
        /// <summary>
        /// Test the property 'PrincipalGovernmentNumber'
        /// </summary>
        [Fact]
        public void PrincipalGovernmentNumberTest()
        {
            // TODO unit test for the property 'PrincipalGovernmentNumber'
        }
        /// <summary>
        /// Test the property 'IncorporationDate'
        /// </summary>
        [Fact]
        public void IncorporationDateTest()
        {
            // TODO unit test for the property 'IncorporationDate'
        }
        /// <summary>
        /// Test the property 'BankAccountHolder'
        /// </summary>
        [Fact]
        public void BankAccountHolderTest()
        {
            // TODO unit test for the property 'BankAccountHolder'
        }
        /// <summary>
        /// Test the property 'BankAccountNumber'
        /// </summary>
        [Fact]
        public void BankAccountNumberTest()
        {
            // TODO unit test for the property 'BankAccountNumber'
        }
        /// <summary>
        /// Test the property 'BankRoutingNumber'
        /// </summary>
        [Fact]
        public void BankRoutingNumberTest()
        {
            // TODO unit test for the property 'BankRoutingNumber'
        }
        /// <summary>
        /// Test the property 'AvgTransactionValue'
        /// </summary>
        [Fact]
        public void AvgTransactionValueTest()
        {
            // TODO unit test for the property 'AvgTransactionValue'
        }
        /// <summary>
        /// Test the property 'MonthlyTransactions'
        /// </summary>
        [Fact]
        public void MonthlyTransactionsTest()
        {
            // TODO unit test for the property 'MonthlyTransactions'
        }
        /// <summary>
        /// Test the property 'MonthlyDisputes'
        /// </summary>
        [Fact]
        public void MonthlyDisputesTest()
        {
            // TODO unit test for the property 'MonthlyDisputes'
        }
        /// <summary>
        /// Test the property 'MonthlyRefunds'
        /// </summary>
        [Fact]
        public void MonthlyRefundsTest()
        {
            // TODO unit test for the property 'MonthlyRefunds'
        }
        /// <summary>
        /// Test the property 'MonthlyChargebacks'
        /// </summary>
        [Fact]
        public void MonthlyChargebacksTest()
        {
            // TODO unit test for the property 'MonthlyChargebacks'
        }
        /// <summary>
        /// Test the property 'UniqueUsers'
        /// </summary>
        [Fact]
        public void UniqueUsersTest()
        {
            // TODO unit test for the property 'UniqueUsers'
        }
        /// <summary>
        /// Test the property 'CompanyPhone'
        /// </summary>
        [Fact]
        public void CompanyPhoneTest()
        {
            // TODO unit test for the property 'CompanyPhone'
        }
        /// <summary>
        /// Test the property 'CompanyCountry'
        /// </summary>
        [Fact]
        public void CompanyCountryTest()
        {
            // TODO unit test for the property 'CompanyCountry'
        }
        /// <summary>
        /// Test the property 'TransactionTime'
        /// </summary>
        [Fact]
        public void TransactionTimeTest()
        {
            // TODO unit test for the property 'TransactionTime'
        }
        /// <summary>
        /// Test the property 'PaymentsFlow'
        /// </summary>
        [Fact]
        public void PaymentsFlowTest()
        {
            // TODO unit test for the property 'PaymentsFlow'
        }
        /// <summary>
        /// Test the property 'BusinessModelDescription'
        /// </summary>
        [Fact]
        public void BusinessModelDescriptionTest()
        {
            // TODO unit test for the property 'BusinessModelDescription'
        }
        /// <summary>
        /// Test the property 'CustomerSupportEmail'
        /// </summary>
        [Fact]
        public void CustomerSupportEmailTest()
        {
            // TODO unit test for the property 'CustomerSupportEmail'
        }
        /// <summary>
        /// Test the property 'BankName'
        /// </summary>
        [Fact]
        public void BankNameTest()
        {
            // TODO unit test for the property 'BankName'
        }
        /// <summary>
        /// Test the property 'BankAccountType'
        /// </summary>
        [Fact]
        public void BankAccountTypeTest()
        {
            // TODO unit test for the property 'BankAccountType'
        }
        /// <summary>
        /// Test the property 'BankHolderType'
        /// </summary>
        [Fact]
        public void BankHolderTypeTest()
        {
            // TODO unit test for the property 'BankHolderType'
        }

    }

}
