/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ReleasePaymentRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReleasePaymentRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReleasePaymentRequestBody
        //private ReleasePaymentRequestBody instance;

        public ReleasePaymentRequestBodyTests()
        {
            // TODO uncomment below to create an instance of ReleasePaymentRequestBody
            //instance = new ReleasePaymentRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReleasePaymentRequestBody
        /// </summary>
        [Fact]
        public void ReleasePaymentRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReleasePaymentRequestBody
            //Assert.IsType<ReleasePaymentRequestBody>(instance);
        }


        /// <summary>
        /// Test the property 'ReleaseAmount'
        /// </summary>
        [Fact]
        public void ReleaseAmountTest()
        {
            // TODO unit test for the property 'ReleaseAmount'
        }
        /// <summary>
        /// Test the property 'FlagRelease'
        /// </summary>
        [Fact]
        public void FlagReleaseTest()
        {
            // TODO unit test for the property 'FlagRelease'
        }

    }

}
