/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace AssemblyPay.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing TokenAuthRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenAuthRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenAuthRequestBody
        //private TokenAuthRequestBody instance;

        public TokenAuthRequestBodyTests()
        {
            // TODO uncomment below to create an instance of TokenAuthRequestBody
            //instance = new TokenAuthRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenAuthRequestBody
        /// </summary>
        [Fact]
        public void TokenAuthRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenAuthRequestBody
            //Assert.IsType<TokenAuthRequestBody>(instance);
        }


        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Fact]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

    }

}
