/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Transaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Transaction
        //private Transaction instance;

        public TransactionTests()
        {
            // TODO uncomment below to create an instance of Transaction
            //instance = new Transaction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Transaction
        /// </summary>
        [Fact]
        public void TransactionInstanceTest()
        {
            // TODO uncomment below to test "IsType" Transaction
            //Assert.IsType<Transaction>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'PayeeName'
        /// </summary>
        [Fact]
        public void PayeeNameTest()
        {
            // TODO unit test for the property 'PayeeName'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'TypeMethod'
        /// </summary>
        [Fact]
        public void TypeMethodTest()
        {
            // TODO unit test for the property 'TypeMethod'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Fact]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'ItemName'
        /// </summary>
        [Fact]
        public void ItemNameTest()
        {
            // TODO unit test for the property 'ItemName'
        }
        /// <summary>
        /// Test the property 'DynamicDescriptor'
        /// </summary>
        [Fact]
        public void DynamicDescriptorTest()
        {
            // TODO unit test for the property 'DynamicDescriptor'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Fact]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'DebitCredit'
        /// </summary>
        [Fact]
        public void DebitCreditTest()
        {
            // TODO unit test for the property 'DebitCredit'
        }
        /// <summary>
        /// Test the property 'Marketplace'
        /// </summary>
        [Fact]
        public void MarketplaceTest()
        {
            // TODO unit test for the property 'Marketplace'
        }
        /// <summary>
        /// Test the property 'Related'
        /// </summary>
        [Fact]
        public void RelatedTest()
        {
            // TODO unit test for the property 'Related'
        }
        /// <summary>
        /// Test the property 'PayeeDetails'
        /// </summary>
        [Fact]
        public void PayeeDetailsTest()
        {
            // TODO unit test for the property 'PayeeDetails'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
