/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace AssemblyPay.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionRelated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionRelatedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionRelated
        //private TransactionRelated instance;

        public TransactionRelatedTests()
        {
            // TODO uncomment below to create an instance of TransactionRelated
            //instance = new TransactionRelated();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionRelated
        /// </summary>
        [Fact]
        public void TransactionRelatedInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionRelated
            //Assert.IsType<TransactionRelated>(instance);
        }


        /// <summary>
        /// Test the property 'Transactions'
        /// </summary>
        [Fact]
        public void TransactionsTest()
        {
            // TODO unit test for the property 'Transactions'
        }

    }

}
