/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace AssemblyPay.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateItemRequestBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateItemRequestBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateItemRequestBody
        //private UpdateItemRequestBody instance;

        public UpdateItemRequestBodyTests()
        {
            // TODO uncomment below to create an instance of UpdateItemRequestBody
            //instance = new UpdateItemRequestBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateItemRequestBody
        /// </summary>
        [Fact]
        public void UpdateItemRequestBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateItemRequestBody
            //Assert.IsType<UpdateItemRequestBody>(instance);
        }


        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'BuyerId'
        /// </summary>
        [Fact]
        public void BuyerIdTest()
        {
            // TODO unit test for the property 'BuyerId'
        }
        /// <summary>
        /// Test the property 'SellerId'
        /// </summary>
        [Fact]
        public void SellerIdTest()
        {
            // TODO unit test for the property 'SellerId'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'CustomDescriptor'
        /// </summary>
        [Fact]
        public void CustomDescriptorTest()
        {
            // TODO unit test for the property 'CustomDescriptor'
        }

    }

}
