/*
 * Assembly API
 *
 * Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@assemblypayments.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;

namespace AssemblyPay.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing WireDetailsWithId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WireDetailsWithIdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WireDetailsWithId
        //private WireDetailsWithId instance;

        public WireDetailsWithIdTests()
        {
            // TODO uncomment below to create an instance of WireDetailsWithId
            //instance = new WireDetailsWithId();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WireDetailsWithId
        /// </summary>
        [Fact]
        public void WireDetailsWithIdInstanceTest()
        {
            // TODO uncomment below to test "IsType" WireDetailsWithId
            //Assert.IsType<WireDetailsWithId>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'WireDetails'
        /// </summary>
        [Fact]
        public void WireDetailsTest()
        {
            // TODO unit test for the property 'WireDetails'
        }

    }

}
